[workspace.package]
version = "0.1.0"
authors = ["Nikolay Volf"]
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/NikVolf/onchain-tests"

[workspace]
resolver = "2"

members = [
    "service",
    "cli",
    "dummy",
    "service/types"
]
