[package]
name = "gear-test-runner"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gtest = { git = "http://github.com/gear-tech/gear" }
anyhow = "1.0"

[[bin]]
name = "gtest"
path = "src/main.rs"
